### ISSUE TITLE
Make RTG Switch off when PAL/NTSC Screens are enabled

### ISSUE THREAD

**Issue by ronybeck** [ApolloTeam-dev/AROS#10]
RTG should be off when PAL/NTSC screens are enabled.  It looks odd if both are enabled and it flips between both seemingly randomly when PAL/NTSC games are loading.

**Comment by alexchaney** [comment]
Is this really a bug or should it be a configurable option?  Many people prefer to have both monitors active.  Should we not let the user decide?

**Comment by amiga23** [comment]
For v2 users it may be usefull as they can connect 2 monitors (AMIGA-RGB and Vampire HDMI). v4 users do not have that "luxury". Default behavior should be to turn RTG off. An option should be added to keep RTG on, maybe that could be done in the ToolTypes of DEVS:Monitors/SAGA?
