### ISSUE TITLE
Build ApolloOS on docker

### ISSUE THREAD

**Issue by walkero-gr** [ApolloTeam-dev/AROS#11]
Hello everyone,
Just to let you know that in case you would like a development environment that works on every OS (Linux, MacOS and Windows) out of the box, I have ready a docker image that is able to build ApolloOS without any issues.

You can find information on how to use it at:
https://github.com/walkero-gr/dde4aros#build-apolloos-for-vampire

This can be used on CI/CD setups for automated builds and deployments, for example when a new tag is created you can use this docker image to build the latest code, and then deploy it to a server, without doing this manually.

I'd love to hear your feedback or in case of any issues, feel free to contact me.

**Comment by hgw77** [comment]
Tested it and is working like a charme :-)

**Comment by walkero-gr** [comment]
Thank you for testing it. I uploaded today newer version of this docker image.
My next step is to have the crosstools needed installed by default inside the image, so that this can be skipped from the compiling process. I believe that this will speed up compiling a lot. 
Can anyone point me any guide for what is needed to be done or which scripts I should check for that?

**Comment by ronybeck** [comment]
Thanks for putting that together.  That is awesome stuff! I have linked your instructions in the wiki.
