### ISSUE TITLE
Copymemquick can only copy 64kb ..

### ISSUE THREAD

**Issue by Lynxxde** [ApolloTeam-dev/AROS#16]
https://github.com/ApolloTeam-dev/AROS/blob/master-new/arch/m68k-all/exec/copymemquick.S
can only copy 64Kb, Row 27 is "subq.w #8,%d0" and should be "subq.l #8,%d0".

**Architecture**
- 68k (including UAE, Vampire cards)
 *CPU**
 - m68k
 
**Version**
Dont got Aros, sorry.

with kind regards, Holger Hippenstiel

**Comment by ronybeck** [comment]
Thanks for reporting this.  This bug and your fix has been verified and committed .  Thanks for your help!
