### ISSUE TITLE
Remove political 'warnings' from code

### ISSUE THREAD

**Issue by nonarkitten** [ApolloTeam-dev/AROS#17]
If you want the 68K Amiga Community in general to accept 68K AROS of AmigaOS, then stuff like this isn't helpful. Messages should appear once at most in the header. Also, note that Vampire isn't a CPU; the AC68080 is.
```
#ifdef NONVAMPIRE
#warning Compiling for non-vampire platform
    /* IF we have AMMX (68080) *and* if AMMX bit in SR is set, save AMMX context */
    if (SysBase->AttnFlags & AFF_68080) // && (ctx->cpu.sr & 0x800))
#endif
            AROS_UFC1NR(void, AMMXRestoreContext, AROS_UFCA(struct AMMXContext *, &ctx->ammx, A0));
```

Try making this more neutral and/or positive.
```
#ifdef AC68080
    if (SysBase->AttnFlags & AFF_68080) && (ctx->cpu.sr & 0x800))
            AROS_UFC1NR(void, AMMXRestoreContext, AROS_UFCA(struct AMMXContext *, &ctx->ammx, A0));
#endif
``

**Comment by ronybeck** [comment]
NOT A BUG.  The code nor its warnings are political.  And those put off by such things will just find something else that puts bees under their bonnet.  Happy to remove the warnings but the code comment stays as it aids in code readability.
