### ISSUE TITLE
datatypes.library

### ISSUE THREAD

**Issue by pcotter72** [ApolloTeam-dev/AROS#20]
**Describe the bug**
ascii files not recognized

**To Reproduce**
multiview doesnt open txt files

**Architecture**
 - Amiga (including UAE, Vampire cards)
 
**CPU**
 
 - m68k
 

**Additional context**
work ok with datatypes.library 45.3 from 14. Feb 2020

**Comment by mattrust** [comment]
This has been fixed in AROS.
