### ISSUE TITLE
Early boot is black and white

### ISSUE THREAD

**Issue by MBeijer** [ApolloTeam-dev/AROS#31]
**Describe the bug**
The screenmode in early boot is black and white

**To Reproduce**
1. Start while holding both mousebuttons to get to early boot screen
2. Click on 'Boot without startup sequence'

**Expected behavior**
The screenmode should at least have 4 colors

**Screenshots**
![Image of issue](https://media.discordapp.net/attachments/730698753513750539/808052959300550666/image0.jpg?width=640&height=480)

**Architecture**
 - Amiga (including UAE, Vampire cards)

**CPU**
 - m68k

**Version**
Release 5

**Comment by ronybeck** [comment]
Thanks for this.  This fix is integrated into the main branch.  Sadly your fix wasn't obvious because it was buried along side lots of other changes.   Could you perhaps separate individual bugs and their corresponding pull requests?
