### ISSUE TITLE
V4Ethernet driver crashes

### ISSUE THREAD

**Issue by ApolloTeam-dev** [ApolloTeam-dev/AROS#7]
V4Ethernet driver crashes very often.  Or at least it leads to some sort of freeze of AROS.  Nothing seen on the serial debug output by default.  Need to activate debugoutput.

**Comment by ronybeck** [comment]
So this has been mostly fixed in the driver itself.  This doesn't need to be investigated from an AROS perspective at this stage.  Closing this ticket.
