### ISSUE TITLE
apolloOS rom disabled rtg support in uae

### ISSUE THREAD

**Issue by nsklaus** [ApolloTeam-dev/AROS#74]
**Describe the bug**
rtg support is currently broken in apolloOS-rom when using uae.
i tried to replace apolloOS-rom with aros-vision-rom (another aros68k distro) and rtg immediately worked.
apolloOS + apollo-rom --> fails
apolloOS + aros-vison-rom --> ok

**To Reproduce**
1. git clone and build apolloOS & apollo-rom
2. use fs-uae to boot apolloOS & apollo-rom
3. see there is no rtg support

**Expected behavior**
other aros68k distros such as aros-vision have proper rtg support.
i expected apolloOS to have rtg support too.

**Screenshots**
![ouya](https://user-images.githubusercontent.com/6810861/174446829-a6800e45-1603-4f5b-8888-41706de4e67e.png)

**Architecture**
linux x86_64 emulating an A4K through fs-uae

**CPU**
 - m68k (uae)

**Version**
Provide the GID ID from AboutAROS (call menu Wanderer>AROS>About)
1b76ad252b (see screenshot)

**Additional context**
for having a comfortable development and testing environment when working on apolloOS sources 
on linux (through uae).

**Comment by WDrijver** [comment]
ApolloOS is targeted specific on Apollo V2 and V4 devices.
ApolloROM by default does not contain generic RTG support (as used by UAE), only SAGA (used by V2/V4)
However a compile time flag is available to compile a ROM with UAE support (incl. RTG) for development use.
